config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  resources :pastes, only: [:new, :create, :show]

  root 'pastes#new'

  get "404", :to => "errors#not_found"
  get "422", :to => "errors#unacceptable"
  get "500", :to => "errors#internal_error"

end

app/models/paste.rb
class Paste < ActiveRecord::Base
  validates_presence_of :title, :body, :uuid

  before_validation do
    self.uuid ||= SecureRandom.hex(4)
  end

  def csv
    CSV.parse(body)
  end

  def to_csv
    CSV.generate(body) { }
  end

  def xls
    body.gsub(",", "\t")
  end

  def to_param
    uuid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def unacceptable
    render status: 422
  end

  def internal_error
    render status: 500
  end
end

app/controllers/pastes_controller.rb
class PastesController < ApplicationController
  before_action :set_paste, only: [:show, :edit, :update, :destroy]

  respond_to :html, :csv

  def show
    respond_to do |format|
      format.html
      format.csv { send_data @paste.to_csv, filename: "#{@paste.title}.csv" }
      format.xls { send_data @paste.xls, filename: "#{@paste.title}.xls"}
    end
  end

  def new
    @paste = Paste.new
    respond_with(@paste)
  end

  def create
    @paste = Paste.new(paste_params)
    @paste.save
    respond_with(@paste)
  end

  private
    def set_paste
      @paste = Paste.find_by(uuid: params[:id])
    end

    def paste_params
      params.require(:paste).permit(:body, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pastes_helper.rb
module PastesHelper
end

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      - if content_for? :title
        = yield(:title)
        = " - "
      Copy and Paste CSV
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    = favicon_link_tag
    = yield(:head)
    = analytics_init if Rails.env.production?

  %body
    = yield

    %br
    %footer
      .row.text-center
        %p
          - if ErrorsController === controller
            Maybe go
            = link_to "back?", root_path
          - else
            From
            = link_to "Hank Stoever", "http://hankstoever.com", target: :_blank
            %br
            Host this app yourself with one click:
            = link_to fa_icon(:github, text: "hstove/copypastecsv"), "https://github.com/hstove/copypastecsv", target: :_blank

app/views/pastes/_form.html.haml
= form_for @paste do |f|
  - if @paste.errors.any?
    #error_explanation
      %h2= "#{pluralize(@paste.errors.count, "error")} prohibited this paste from being saved:"
      %ul
        - @paste.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-md-8.col-md-offset-2
      = f.text_field :title, class: 'form-control', placeholder: "Give it a title", autofocus: true
  %br
  .row
    .col-md-8.col-md-offset-2
      = f.text_area :body, class: 'form-control', placeholder: "Copy your CSV File here!"
  %br
  .actions.row
    .col-md-12.text-center
      = f.submit 'Save', class: 'btn btn-success'

app/views/pastes/edit.html.haml
%h1 Editing paste

= render 'form'

= link_to 'Show', @paste
\|
= link_to 'Back', pastes_path

app/views/pastes/index.html.haml
%h1 Listing pastes

%table
  %thead
    %tr
      %th Body
      %th Title
      %th
      %th
      %th
      
  %tbody
    - @pastes.each do |paste|
      %tr
        %td= paste.body
        %td= paste.title
        %td= link_to 'Show', paste
        %td= link_to 'Edit', edit_paste_path(paste)
        %td= link_to 'Destroy', paste, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Paste', new_paste_path

app/views/pastes/new.html.haml
.row.text-center
  .col-md-12
    %h1 Paste Your CSV

= render 'form'

app/views/pastes/show.html.haml
- content_for(:title) { @paste.title }
.row.text-center
  .col-md-12
    %h1= @paste.title
    %p.small.label.label-default
      = time_ago_in_words @paste.created_at
      ago
%br

.row
  .col-md-12.text-center
    .btn-group
      = link_to 'Download .CSV', paste_path(@paste, format: 'csv'), class: 'btn btn-primary'
      = link_to 'Download .XLS', paste_path(@paste, format: 'xls'), class: 'btn btn-success'
%br

.row
  .col-md-10.col-md-offset-1
    %table.table.table-bordered.table-striped
      %tbody
        - @paste.csv.each do |row|
          %tr
            - row.each do |col|
              %td= col